### ISSUE TITLE
setup的代码有点问题，请修复

### ISSUE THREAD

**Issue by luckworld** [JoinQuant/jqdatasdk#16]
requirements = [str(ir.req) for ir in parse_requirements("requirements.txt", session=False)]

if sys.version_info.major == 2:
    requirements = [str(ir.req) for ir in parse_requirements("requirements-py2.txt", session=False)]

在代码环境是python2的时候，由于在py2下的没有req属性，在进if语句前，会直接抛异常，安装失败；可改成if-else结构

**Comment by onlyzf** [comment]
command: /Users/user/miniconda3/envs/quant/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/h3/m_rgq1zj44s74nbzgwn9j0lh0000gn/T/pip-install-tmydcv0r/jqdatasdk/setup.py'"'"'; __file__='"'"'/private/var/folders/h3/m_rgq1zj44s74nbzgwn9j0lh0000gn/T/pip-install-tmydcv0r/jqdatasdk/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/h3/m_rgq1zj44s74nbzgwn9j0lh0000gn/T/pip-pip-egg-info-47je1kg3
         cwd: /private/var/folders/h3/m_rgq1zj44s74nbzgwn9j0lh0000gn/T/pip-install-tmydcv0r/jqdatasdk/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/h3/m_rgq1zj44s74nbzgwn9j0lh0000gn/T/pip-install-tmydcv0r/jqdatasdk/setup.py", line 27, in <module>
        requirements = [str(ir.req) for ir in parse_requirements("requirements.txt", session=False)]
      File "/private/var/folders/h3/m_rgq1zj44s74nbzgwn9j0lh0000gn/T/pip-install-tmydcv0r/jqdatasdk/setup.py", line 27, in <listcomp>
        requirements = [str(ir.req) for ir in parse_requirements("requirements.txt", session=False)]
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
