### ISSUE TITLE
最新版jqdatasdk无法获取行业指数和概念指数的行情数据

### ISSUE THREAD

**Issue by yoyo182487329** [JoinQuant/jqdatasdk#9]
无法获取行业指数的行情数据：
~~~
jq.get_price('801010','2019-01-01','2019-01-10')
Traceback (most recent call last):

  File "<ipython-input-55-1e1b2cc4592b>", line 1, in <module>
    jq.get_price('801010','2019-01-01','2019-01-10')

  File "/home/luyao/anaconda3/lib/python3.6/site-packages/jqdatasdk/utils.py", line 223, in _wrapper
    return func(*args, **kwargs)

  File "/home/luyao/anaconda3/lib/python3.6/site-packages/jqdatasdk/api.py", line 29, in get_price
    return JQDataClient.instance().get_price(**locals())

  File "/home/luyao/anaconda3/lib/python3.6/site-packages/jqdatasdk/client.py", line 143, in <lambda>
    return lambda **kwargs: self(method, **kwargs)

  File "/home/luyao/anaconda3/lib/python3.6/site-packages/jqdatasdk/client.py", line 138, in __call__
    raise err

Exception: 找不到标的801010
~~~
无法获得概念指数的行情数据：
~~~
jq.get_price('GN001','2019-01-01','2019-01-10')
Traceback (most recent call last):

  File "<ipython-input-57-8ad36cc698fb>", line 1, in <module>
    jq.get_price('GN001','2019-01-01','2019-01-10')

  File "/home/luyao/anaconda3/lib/python3.6/site-packages/jqdatasdk/utils.py", line 223, in _wrapper
    return func(*args, **kwargs)

  File "/home/luyao/anaconda3/lib/python3.6/site-packages/jqdatasdk/api.py", line 29, in get_price
    return JQDataClient.instance().get_price(**locals())

  File "/home/luyao/anaconda3/lib/python3.6/site-packages/jqdatasdk/client.py", line 143, in <lambda>
    return lambda **kwargs: self(method, **kwargs)

  File "/home/luyao/anaconda3/lib/python3.6/site-packages/jqdatasdk/client.py", line 138, in __call__
    raise err

Exception: 找不到标的GN001
~~~

**Comment by vhysug** [comment]
get_price暂不支持直接使用行业/概念指数直接获取行情信息。
可以使用
```python
stocks = jq.get_industry_stocks('行业代码', date='2019-01-01')  # 获取相关成分股
jq.get_price(stocks, '2019-01-01', '2019-01-10')  # 获取成分股行情
```

具体使用方法见API说明文档：https://www.joinquant.com/help/api/help?name=api#%E6%95%B0%E6%8D%AE%E8%8E%B7%E5%8F%96%E5%87%BD%E6%95%B0
